function escapeHtml(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

export function humanSummary(result) {
  const m = result.metrics;
  const lines = [
    `WeaveCheck: ${result.model.name}`,
    `Status: ${result.status.toUpperCase()}`,
    `Explored: ${m.statesExplored} states, ${m.transitions} transitions, depth ${m.maxDepth}`,
    `Terminal: ${m.terminalStates} states, ${m.uniqueOutcomes} unique shared outcomes`,
    `Findings: ${m.issues} issues, ${m.deadlocks} deadlocks`,
  ];
  if (result.limits.truncated) lines.push(`Limit reached: ${result.limits.maxStates} states; result is inconclusive`);
  for (const issue of result.issues.slice(0, 5)) {
    lines.push(`- ${issue.kind}/${issue.id}: ${issue.message} (${issue.trace.length} steps)`);
  }
  return lines.join("\n");
}

export function htmlReport(result) {
  const safeJson = JSON.stringify(result).replaceAll("<", "\\u003c");
  const status = escapeHtml(result.status.toUpperCase());
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>WeaveCheck | ${escapeHtml(result.model.name)}</title>
<style>
:root{color-scheme:dark;--bg:#0a1020;--panel:#111a31;--line:#263556;--text:#eef4ff;--muted:#9fb0cf;--accent:#7ce7c4;--bad:#ff7a90;--warn:#ffd37c}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#152850 0,var(--bg) 42%);color:var(--text);font:15px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace}main{width:min(1120px,calc(100% - 32px));margin:40px auto 72px}header{display:grid;gap:10px;margin-bottom:24px}.eyebrow{color:var(--accent);letter-spacing:.14em;text-transform:uppercase;font-size:12px}h1{font:700 clamp(32px,6vw,64px)/1.02 system-ui,sans-serif;margin:0;letter-spacing:-.04em}.lede{color:var(--muted);max-width:720px;margin:0}.status{display:inline-flex;width:max-content;border:1px solid var(--line);border-radius:999px;padding:6px 12px;font-weight:800}.status.safe{color:var(--accent)}.status.unsafe{color:var(--bad)}.status.inconclusive{color:var(--warn)}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px;margin:24px 0}.metric,.panel{background:linear-gradient(145deg,rgba(21,34,62,.94),rgba(14,23,43,.94));border:1px solid var(--line);border-radius:16px}.metric{padding:16px}.metric strong{display:block;font:700 26px/1 system-ui,sans-serif}.metric span{color:var(--muted);font-size:12px}.panel{padding:20px;margin-top:16px}h2{font:700 20px system-ui,sans-serif;margin:0 0 14px}.finding{border-left:3px solid var(--bad);padding:12px 14px;margin:10px 0;background:#0b1429;border-radius:0 10px 10px 0}.finding button{background:transparent;color:var(--accent);border:1px solid var(--line);padding:6px 10px;border-radius:8px;cursor:pointer}.trace{display:none;margin-top:12px;overflow:auto}.trace.open{display:block}table{border-collapse:collapse;width:100%;min-width:620px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:9px;vertical-align:top}th{color:var(--muted);font-size:12px}code{color:#c5d7ff}.empty{color:var(--muted)}footer{color:var(--muted);margin-top:28px;font-size:12px}@media(max-width:520px){main{width:min(100% - 20px,1120px);margin-top:22px}.panel{padding:14px}}
</style>
</head>
<body><main>
<header><div class="eyebrow">Bounded concurrency evidence</div><h1>${escapeHtml(result.model.name)}</h1><p class="lede">${escapeHtml(result.model.description || "Explicit-state exploration of every reachable scripted interleaving within the configured bound.")}</p><div class="status ${escapeHtml(result.status)}">${status}</div></header>
<section class="metrics" id="metrics"></section>
<section class="panel"><h2>Findings</h2><div id="findings"></div></section>
<section class="panel"><h2>Reachable terminal outcomes</h2><div id="outcomes"></div></section>
<footer>Generated by WeaveCheck 0.1.0. A SAFE result applies only to this finite model and explored bound.</footer>
</main>
<script type="application/json" id="report-data">${safeJson}</script>
<script>
const report=JSON.parse(document.getElementById('report-data').textContent);const esc=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metrics=[['States',report.metrics.statesExplored],['Transitions',report.metrics.transitions],['Max depth',report.metrics.maxDepth],['Terminal states',report.metrics.terminalStates],['Outcomes',report.metrics.uniqueOutcomes],['Findings',report.metrics.issues]];document.getElementById('metrics').innerHTML=metrics.map(([k,v])=>'<div class="metric"><strong>'+esc(v)+'</strong><span>'+esc(k)+'</span></div>').join('');
const findings=document.getElementById('findings');if(!report.issues.length)findings.innerHTML='<p class="empty">No invariant failures, expectation failures, execution errors, lock leaks, or deadlocks were reachable.</p>';else findings.innerHTML=report.issues.map((issue,i)=>'<article class="finding"><strong>'+esc(issue.kind)+' / '+esc(issue.id)+'</strong><p>'+esc(issue.message)+'</p><code>'+esc(JSON.stringify(issue.state.shared))+'</code><p><button data-trace="'+i+'">Replay '+issue.trace.length+' steps</button></p><div class="trace" id="trace-'+i+'"><table><thead><tr><th>#</th><th>Actor</th><th>Operation</th><th>Label</th><th>Shared after</th><th>Locks after</th></tr></thead><tbody>'+issue.trace.map((event,j)=>'<tr><td>'+(j+1)+'</td><td>'+esc(event.actor)+'</td><td>'+esc(event.op)+'</td><td>'+esc(event.label)+'</td><td><code>'+esc(JSON.stringify(event.shared))+'</code></td><td><code>'+esc(JSON.stringify(event.locks))+'</code></td></tr>').join('')+'</tbody></table></div></article>').join('');
document.querySelectorAll('[data-trace]').forEach(button=>button.addEventListener('click',()=>document.getElementById('trace-'+button.dataset.trace).classList.toggle('open')));
const outcomes=document.getElementById('outcomes');outcomes.innerHTML=report.outcomes.length?'<table><thead><tr><th>#</th><th>Shared state</th><th>Shortest witness</th></tr></thead><tbody>'+report.outcomes.map((outcome,i)=>'<tr><td>'+(i+1)+'</td><td><code>'+esc(JSON.stringify(outcome.shared))+'</code></td><td>'+outcome.trace.length+' steps</td></tr>').join('')+'</tbody></table>':'<p class="empty">No terminal state was reached.</p>';
</script></body></html>`;
}
